### ISSUE TITLE
Internal error is thrown when update() violates constraint

### ISSUE THREAD

**Issue by RKrahl** [icatproject/icat.server#223] opened 2019-03-18 09:21 UTC
When trying to create an object that violates the constraint of the corresponding class (e.g. the object already exists), an `ObjectExistsError` is thrown as expected. But when trying to update an existing object in a way that violates the same constraint, an `InternalError` is thrown. With a freshly installed, empty ICAT one gets:
```python
>>> facility = client.new("facility", name="Example")
>>> facility.create()
>>> instrument1 = client.new("instrument", name="Instrument A", facility=facility)
>>> instrument1.create()
>>> instrument2 = client.new("instrument", name="Instrument A", facility=facility)
>>> instrument2.create()
ERROR:suds.client:<suds.sax.document.Document object at 0x7f8c92b1c198>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hmi/test/python-icat-0.14.2/build/lib/icat/entity.py", line 414, in create
    self.id = self.client.create(self)
  File "/hmi/test/python-icat-0.14.2/build/lib/icat/client.py", line 427, in create
    raise translateError(e)
icat.exception.ICATObjectExistsError: Instrument exists with facility = 'Facility:1', name = 'Instrument A'
>>> instrument2 = client.new("instrument", name="Instrument B", facility=facility)
>>> instrument2.create()
>>> instrument2.name = "Instrument A"
>>> instrument2.update()
ERROR:suds.client:<suds.sax.document.Document object at 0x7f8c92b23be0>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hmi/test/python-icat-0.14.2/build/lib/icat/entity.py", line 420, in update
    self.client.update(self)
  File "/hmi/test/python-icat-0.14.2/build/lib/icat/client.py", line 563, in update
    raise translateError(e)
icat.exception.ICATInternalError: Unexpected DB response class javax.persistence.PersistenceException Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-Instrument A' for key 'UNQ_INSTRUMENT_0'
Error Code: 1062
Call: UPDATE INSTRUMENT SET MOD_TIME = ?, NAME = ? WHERE (ID = ?)
        bind => [3 parameters bound]
Query: UpdateObjectQuery(Instrument:3)
```
The first error is expected as an instrument with that name already exist. But the `update()` call that violates the very same constraint should yield the same `ObjectExistsError` rather then an `InternalError`.  Apparently this error condition is checked in the `create()` call, but not in the `update()` call in icat.server.

**Comment by RKrahl** [comment] 2019-03-18 09:24
Note that I discovered this issue in the current release version 4.9.3. I also checked that it is still present in the recent 4.10.0 snapshot.

**Comment by stuartpullinger** [comment] 2019-03-21 12:28
The create methods call 'persist' on of the EntityBeanManager with the Bean which should be persisted to the database. This puts the Bean in the database. If it already exists, the persist method raises an EntityExistsException. The create methods catch this and throw a new `IcatException(IcatException.IcatExceptionType.OBJECT_ALREADY_EXISTS, ...`. The update method works differently. It creates a new managed Bean and iterates over its fields, updating them from the provided update object.

In the example above, the updated object violated one of the uniqueness constraints, so the update caused an exception. The MySQL database threw a ConstraintViolationException which passed up through an Eclipse Database Exception, a Java PersistenceException to an ICATInternalError exception. The problem here is that the Exception we get is too generic to be sure that it was caused by the Object existing and the more specific exception is particular to the database implementation.

I don't want to throw an ObjectExistsError based on a PersistenceException which could have been caused by other errors. And I don't want to inspect the Exception for a MySql-specific exception because that won't work on Oracle or any other database. For this reason, I'm closing this and marking it as "Won't Fix". Please feel free to re-open it if you see another possible solution.

**Closed by stuartpullinger** 2019-03-21 12:28 UTC
Labels: bug, wontfix

**Comment by RKrahl** [comment] 2019-03-22 13:46
That's too bad. I have the case in our workflows where I need to handle this error condition. If I can't do that by catching `ObjectExistsError`, it will get much more complicated.
