### ISSUE TITLE
Add an attribute "orcid" to User

### ISSUE THREAD

**Issue by RKrahl** [icatproject/icat.server#167] opened 2016-03-16 14:28 UTC
It would be useful to be able to record the [ORCID iD](http://orcid.org/) with a user.

**Comment by fisherab** [comment] 2016-03-16 19:01
This could easily be added to 4.7 as there are already a couple of scheme
changes. What is the use case for it - or in general how much information
should be in ICAT and how much in the user office. If we add the orcid id
 I might be inclined to remove the user name from the user table then
anything else about the user is obtained from the user office based on the
orcid id.

Steve

**Comment by RKrahl** [comment] 2016-03-17 07:41
The use case would be to disambiguate users in case of equal or similar names in general and to improve the reliability in attributing scientific output to the correct person.  One practical application might be adding links to ORCID profiles of the authors in the landing pages for data publications generated out of ICAT.

I agree that there is some degree of redundancy with fullName.  I'd favor to have both in the ICAT schema nevertheless for two reasons:

1. The preconditions at different sites are different.  Not all sites are collecting ORCID iDs in the user office.  Those that do might not make the indication of the ORCID iD obligatory for all users.  In both cases we cannot assume that the orcid attribute is set for all users.  So we would need the fullName at least as a fallback.

2. I'd like the data in ICAT to be self-sufficient, independent from other data bases such as the user office, at least for core tasks of ICAT.  It simplifies the development of tools a lot, if these tools need only to connect to one single data source.  And I'd consider providing the data for the landing page for data publications as core task of ICAT with this regard.

**Comment by Softey** [comment] 2016-03-17 08:32
Another case for keeping the fullName is making displayed data on the dashboard easier to read. It gives the data a bit more context when you can see that Dr Dog has downloaded xyz then uows/123456 has downloaded xyz.

**Comment by tomgriffinstfc** [comment] 2016-03-17 10:01
A similar point came up in a recent discussion with ESRF.
A number of extra fields could perhaps usefully be added to the USER table - email, affiliation/organization, ORCID are the ones I can think of now.

Certainly ORCID cannot be the only field in USER as it is not required by all (any?) facilities yet.

In most cases, these fields would be a duplicate of data in the user office, but I agree with Rolf that tools should be able to see ICAT as a single point for all data.

Another option might be to consider a user-database plugin system such that the data is kept in the user office, but ICAT accesses it via a common interface (the plugin) to get the information - similar to the authn plugins.

We have to be careful with permissions around user data: generally the user table needs to be quite widely readable in order to show investigators (investigationusers). Adding more fields to the USER table could risk leaking sensitive information.

**Comment by RKrahl** [comment] 2016-03-17 10:22
I agree with Tom that the disclosure of sensitive information is an issue with the user table.  I even have this table world readable, because I want the PIs to be able to manage access permissions on their investigations themselves.  If they want to grant access to someone, they need to be able to search the entry for this person from the user table.

On the other hand, site admins still have the option to leave some of the fields empty if they consider this information too sensitive.

**Comment by fisherab** [comment] 2016-04-04 13:28
I propose to add add "orcid"

**Comment by fisherab** [comment] 2016-04-04 13:29
I meant to say: I propose to add orcid and email with the expectation that many sites will leave this fields blank.

**Comment by fisherab** [comment] 2016-04-06 08:24
The general feeling on the web is that email is now preferred to e-mail and that the use of the spelling without the hyphen is increasing so I will call the attribute email. ORCID (Open Researcher and Contributor ID) call their invention ORCID iD which has both strange capitalization, a space and a redundant ID. In addition their logo is ORCid. If I camel case the full name it we get orcidId alternatively it could be just orcid. Which do people prefer. I think I prefer orcidId, as ORCID is the name of the organisation.

**Comment by Softey** [comment] 2016-04-06 08:29
I would lean towards orcidId to match the naming conventions of the other fields in the ICAT with the camel case

**Comment by tomgriffinstfc** [comment] 2016-04-06 08:37
orcid themselves just use 'orcid' in code 
https://github.com/ORCID/

**Comment by RKrahl** [comment] 2016-04-06 08:41
To a german, using "email" to denote e-mail always sounds funny, because the former is an existing german word and means vitreous enamel.  But nevertheless, we don't have hyphens in attribute names yet and I'd prefer keeping this restriction over lingual esthetics, so I vote for "email".

I agree that the naming conventions of ORCID with the redundant usage of id in "ORCID iD" is strange. I'm undecided between "orcid" and "orcidId" and happy with both options.

**Closed** 2016-04-06 13:55 UTC
